{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Language.
--   Generated by the BNF converter.

module Language.Print where

import qualified Language.Abs
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Language.Abs.Ident where
  prt _ (Language.Abs.Ident i) = doc (showString i)
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Language.Abs.TypeName where
  prt i e = case e of
    Language.Abs.TSimpleTypeName id -> prPrec i 0 (concatD [prt 0 id])
    Language.Abs.TPolymorphicTypeName id typenames -> prPrec i 0 (concatD [prt 0 id, doc (showString "<"), prt 0 typenames, doc (showString ">")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Language.Abs.TypeName] where
  prt = prtList

instance Print Language.Abs.Expr where
  prt i e = case e of
    Language.Abs.EAdd expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "+"), prt 7 expr2])
    Language.Abs.ESub expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "-"), prt 7 expr2])
    Language.Abs.EMul expr1 expr2 -> prPrec i 7 (concatD [prt 7 expr1, doc (showString "*"), prt 8 expr2])
    Language.Abs.EDiv expr1 expr2 -> prPrec i 7 (concatD [prt 7 expr1, doc (showString "/"), prt 8 expr2])
    Language.Abs.EEq expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "=="), prt 6 expr2])
    Language.Abs.ENotEq expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "!="), prt 6 expr2])
    Language.Abs.ELt expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "<"), prt 6 expr2])
    Language.Abs.EGt expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString ">"), prt 6 expr2])
    Language.Abs.ELtEq expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "<="), prt 6 expr2])
    Language.Abs.EGtEq expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString ">="), prt 6 expr2])
    Language.Abs.EInt n -> prPrec i 10 (concatD [prt 0 n])
    Language.Abs.EOr expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, doc (showString "or"), prt 5 expr2])
    Language.Abs.EAnd expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, doc (showString "and"), prt 5 expr2])
    Language.Abs.ENot expr -> prPrec i 7 (concatD [doc (showString "not"), prt 8 expr])
    Language.Abs.ETrue -> prPrec i 10 (concatD [doc (showString "true")])
    Language.Abs.EFalse -> prPrec i 10 (concatD [doc (showString "false")])
    Language.Abs.ELambda id typename expr -> prPrec i 9 (concatD [doc (showString "("), prt 0 id, doc (showString ":"), prt 0 typename, doc (showString "->"), prt 10 expr, doc (showString ")")])
    Language.Abs.EVar id -> prPrec i 10 (concatD [prt 0 id])
    Language.Abs.EFunCall expr exprs -> prPrec i 9 (concatD [prt 9 expr, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Language.Abs.EList exprs -> prPrec i 4 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    Language.Abs.ECons expr1 expr2 -> prPrec i 4 (concatD [prt 4 expr1, doc (showString "::"), prt 5 expr2])
    Language.Abs.ENil -> prPrec i 5 (concatD [doc (showString "nil")])
    Language.Abs.EIfte expr1 expr2 expr3 -> prPrec i 3 (concatD [doc (showString "if"), prt 3 expr1, doc (showString "then"), prt 3 expr2, doc (showString "else"), prt 3 expr3])
    Language.Abs.ESemicolon stmt expr -> prPrec i 1 (concatD [prt 0 stmt, doc (showString ";"), prt 2 expr])
    Language.Abs.EMatch expr matchclauses -> prPrec i 0 (concatD [doc (showString "match"), prt 1 expr, prt 0 matchclauses])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Language.Abs.Expr] where
  prt = prtList

instance Print Language.Abs.Stmt where
  prt i e = case e of
    Language.Abs.SDeclVar id expr -> prPrec i 0 (concatD [doc (showString "val"), prt 0 id, doc (showString "="), prt 0 expr])
    Language.Abs.SDeclFun id ids expr -> prPrec i 0 (concatD [doc (showString "fun"), prt 0 id, doc (showString "("), prt 0 ids, doc (showString ")"), doc (showString "{"), prt 0 expr, doc (showString "}")])

instance Print [Language.Abs.Ident] where
  prt = prtList

instance Print Language.Abs.MatchClause where
  prt i e = case e of
    Language.Abs.MMatchClause expr1 expr2 -> prPrec i 0 (concatD [doc (showString "as"), prt 1 expr1, doc (showString "~>"), prt 2 expr2])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Language.Abs.MatchClause] where
  prt = prtList

